### ISSUE TITLE
dataset download

### ISSUE THREAD

**Issue by huangdaichui** [MarkMoHR/Awesome-Sketch-Synthesis#2]
Thanks for your work.
But the download address of QMUL-Shoe-Chair-V2 can not open.
Would you mind provide the datasets ?
Thanks for your help

**Comment by MarkMoHR** [comment]
The download link is updated: [https://drive.google.com/file/d/15s2BR-QwLgX_DObQBrYlUlZqUU90EL9G/view](https://drive.google.com/file/d/15s2BR-QwLgX_DObQBrYlUlZqUU90EL9G/view)
