### ISSUE TITLE
New paper

### ISSUE THREAD

**Issue by Chanuku** [MarkMoHR/Awesome-Sketch-Synthesis#4]
Hi thanks for the awesome page

I have the new paper which is follow-up study of "Reference based sketch extraction via attention mechanism"

new paper's title is "Semi-supervised reference-based sketch extraction using a contrastive learning framework"

it is accepted to upcoming siggraph 2023 journal track

project page : https://chanuku.github.io/Semi_ref2sketch/
code : https://github.com/Chanuku/semi_ref2sketch_code
dataset (4skst) : https://github.com/Chanuku/4skst

Thank you

**Comment by MarkMoHR** [comment]
Done. Thanks!
