### ISSUE TITLE
New papers about 3D wire art 

### ISSUE THREAD

**Issue by WinKawaks** [MarkMoHR/Awesome-Sketch-Synthesis#6]
Hi, thank you for this awesome project!

Here are some papers about 3D wire art:

> Wired Perspectives: Multi-View Wire Art Embraces Generative AI -- CVPR  2024
> Fabricable 3D Wire Art -- Siggraph 2024

Could you please add these works to this project? These works optimize the 3D curves based on a 2D renderer and 2D sketch synthesis approaches. Even though these is no "sketch" in the title, the "wire art" could  be treated as 3D sketches.

**Comment by MarkMoHR** [comment]
Done. Thanks!
